version: "3"
services:
  # # MySQLの設定
  # db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # 環境変数（.env）から参照
  #     MYSQL_DATABASE: ${MYSQL_DB} # 環境変数（.env）から参照
  #     MYSQL_USER: ${MYSQL_USER} # 環境変数（.env）から参照
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD} # 環境変数（.env）から参照
  #     TZ: "Asia/Tokyo"
  #   volumes:
  #     # db-dataというボリュームをコンテナ内の/var/lib/mysqlにマウントする
  #     - db-data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  # Railsの設定
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      # カレントディレクトリの内容をコンテナ内の/appにマウントする
      - .:/app
    env_file:
      - .env
    ports:
      - ${RAILS_PORT}:3000 # 環境変数（.env）から参照
    # コンテナを起動したままにする
    tty: true
    # 標準入出力とエラー出力をコンテナに結び付ける設定
    stdin_open: true
    # dbサービスを起動してからwebサービスを起動させる
    # depends_on:
    #   - db
# volumes:
#   db-data: